package ca.uwaterloo.ece.bicer;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Set;

import org.junit.Test;
import ca.uwaterloo.ece.bicer.data.BIChange;
import ca.uwaterloo.ece.bicer.utils.Utils;

/*
 * Compare biChanged generated by BICER and sanitized one. Since the sanitized one has bugs in BISha1 as there is a bug (blamed in a wrong line num) in previous tool.
 * By the comparison, we can identify lines that require manual analysis whether a line is actually BI line.
 * by 'j22nam' at '27/05/16 5:45 PM' with Gradle 2.13
 *
 * @author j22nam, @date 27/05/16 5:45 PM
 */
public class BiChangeOldPathFixerTest {
    @Test public void testSomeLibraryMethod() {
    	
    	String project ="jackrabbit";
    	String dir = System.getProperty("user.home") + "/Documents/ODP/projects/" + project +"/";
        
    	String pathForBIChangesFromGoogleSheet = dir + "biChangesOldToolAll.txt";
    	String pathForBIChangesFromDB = dir +"biChanges.txt";
    	
    	ArrayList<BIChange> biChangesAll = loadBIChanges(pathForBIChangesFromGoogleSheet, true);
    	ArrayList<BIChange> biChangesFromDB = loadBIChanges(pathForBIChangesFromDB, true);
    	
    	HashMap<String,ArrayList<BIChange>> mapBIChangesFromDB = new HashMap<String,ArrayList<BIChange>>(); // key fixSha1 + path + lineNum + line
    	    	
    	for(BIChange biChange:biChangesFromDB){
    		String key = biChange.getFixSha1() + biChange.getPath() + biChange.getLineNumInPrevFixRev() + biChange.getLine().trim();
    		if(!mapBIChangesFromDB.containsKey(key)){
    			ArrayList<BIChange> arrBIChange = new ArrayList<BIChange>();
    			arrBIChange.add(biChange);
    			mapBIChangesFromDB.put(key, arrBIChange);
    		} else{
    			mapBIChangesFromDB.get(key).add(biChange);
    		}
    	}
    	
    	ArrayList<BIChange> biChangesAllWithCorrectOldPath = new ArrayList<BIChange>();
    	ArrayList<BIChange> missingbiChangesFromDB = new ArrayList<BIChange>();
    	for(BIChange biChange:biChangesAll){
    		String key = biChange.getFixSha1() + biChange.getPath() + biChange.getLineNumInPrevFixRev() + biChange.getLine().trim();
    		
    		if(!mapBIChangesFromDB.containsKey(key)){
    			missingbiChangesFromDB.add(biChange);
    			continue;
    		}
    		biChangesAllWithCorrectOldPath.add(mapBIChangesFromDB.get(key).get(0));	
    	}
    	
    	System.out.println("BIChanges from old tool: " + biChangesAll.size() );
    	System.out.println("BIChanges from DB: " + biChangesFromDB.size() );
    	
    	for(BIChange biChange:biChangesAllWithCorrectOldPath)
    		System.out.println(biChange.getRecordWithoutLineNumInPrevFix());
	}
    
    private ArrayList<BIChange> loadBIChanges(String path,boolean forSanitizer) {
		ArrayList<String> BIChangeInfo = Utils.getLines(path, true); // Sanitizer file does not have header line, so remove it.
		ArrayList<BIChange> biChanges = new ArrayList<BIChange>();
		for(String info: BIChangeInfo){
			biChanges.add(new BIChange(info,forSanitizer));
		}
		
		return biChanges;
	}
}
